#!/usr/bin/env python3
"""
Config generator for llama-server with model duplication.
Generates config.ini with GPU and CPU variants for each model.
"""

import argparse
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class ModelConfig:
  """Configuration for a single model instance."""

  name: str
  path: str
  ngl: int
  batch_size: int = 512
  ctx_size: int = 32768
  num_threads: int = 8
  flash_attn: bool = True
  mlock: bool = True


@dataclass
class ModelGroup:
  """A model with both GPU and CPU variants."""

  base_name: str
  gpu: Optional[ModelConfig]
  cpu: ModelConfig
  common_params: dict = field(default_factory=dict)


class ConfigGenerator:
  """Generates llama-server config.ini with model duplication."""

  def __init__(
    self,
    models_dir: Path = Path("/data/ai-stack/llm/models"),
    output_path: Path = Path("/app/config/config.ini"),
    large_model_threshold: int = 20 * 1024**3,  # 20GB
    default_batch_size: int = 512,
    default_ctx_size: int = 32768,
    default_num_threads: int = 8,
    gpu_ngl: int = 99,
    cpu_ngl: int = 0,
    model_routing: Optional[dict[str, str]] = None,
  ):
    self.models_dir = models_dir
    self.output_path = output_path
    self.large_model_threshold = large_model_threshold
    self.default_batch_size = default_batch_size
    self.default_ctx_size = default_ctx_size
    self.default_num_threads = default_num_threads
    self.gpu_ngl = gpu_ngl
    self.cpu_ngl = cpu_ngl
    self.model_routing = model_routing or {}

    self.model_groups: dict[str, ModelGroup] = {}

  def _should_use_gpu(self, model_name: str) -> bool:
    """Determine if model should have GPU variant."""
    routing = self.model_routing.get(model_name, "auto")
    if routing == "cpu":
      return False
    if routing == "gpu":
      return True
    return True  # auto

  def discover_models(self) -> None:
    """Discover all GGUF models in the models directory."""
    model_files = list(self.models_dir.glob("*.gguf"))

    for model_path in model_files:
      model_name = model_path.stem
      file_size = model_path.stat().st_size

      # Large models: CPU only
      if file_size > self.large_model_threshold:
        gpu_config = None
      else:
        # Smaller models: both GPU and CPU
        gpu_config = ModelConfig(
          name=model_name,
          path=str(model_path),
          ngl=self.gpu_ngl,
          batch_size=self.default_batch_size,
          ctx_size=self.default_ctx_size,
          num_threads=self.default_num_threads,
        )

      # CPU variant always exists
      cpu_config = ModelConfig(
        name=model_name,
        path=str(model_path),
        ngl=self.cpu_ngl,
        batch_size=self.default_batch_size,
        ctx_size=self.default_ctx_size,
        num_threads=max(self.default_num_threads * 2, 16),  # More threads for CPU
      )

      group = ModelGroup(
        base_name=model_name,
        gpu=gpu_config,
        cpu=cpu_config,
        common_params={"flash_attn": True, "mlock": True},
      )
      self.model_groups[model_name] = group

      if gpu_config:
        print(f"  Added: {model_name} (GPU+CPU, {file_size / 1024**3:.2f}GB)")
      else:
        print(f"  Added: {model_name} (CPU only, {file_size / 1024**3:.2f}GB)")

  def generate_config(self) -> str:
    """Generate the config.ini content."""
    lines = ["# Auto-generated by ConfigGenerator - DO NOT EDIT", ""]

    for group in self.model_groups.values():
      # GPU variant
      if group.gpu:
        lines.extend(
          [
            f"[{group.gpu.name}:gpu]",
            f"path={group.gpu.path}",
            f"ngl={group.gpu.ngl}",
            f"batch_size={group.gpu.batch_size}",
            f"ctx-size={group.gpu.ctx_size}",
            f"num_threads={group.gpu.num_threads}",
            f"flash_attn={'1' if group.gpu.flash_attn else '0'}",
            f"mlock={'1' if group.gpu.mlock else '0'}",
            "",
          ]
        )

      # CPU variant
      lines.extend(
        [
          f"[{group.cpu.name}:cpu]",
          f"path={group.cpu.path}",
          f"ngl={group.cpu.ngl}",
          f"batch_size={group.cpu.batch_size}",
          f"ctx-size={group.cpu.ctx_size}",
          f"num_threads={group.cpu.num_threads}",
          f"flash_attn={'1' if group.cpu.flash_attn else '0'}",
          f"mlock={'1' if group.cpu.mlock else '0'}",
          "",
        ]
      )

    return "\n".join(lines)

  def write_config(self) -> None:
    """Write the config.ini file."""
    config_content = self.generate_config()
    self.output_path.parent.mkdir(parents=True, exist_ok=True)
    self.output_path.write_text(config_content)
    print(f"\nConfig written to {self.output_path}")

  def print_summary(self) -> None:
    """Print a summary of the generated configuration."""
    print("\n=== Configuration Summary ===")
    print(f"Models directory: {self.models_dir}")
    print(f"Output path: {self.output_path}")
    print(f"Total models: {len(self.model_groups)}")

    gpu_count = sum(1 for g in self.model_groups.values() if g.gpu)
    cpu_only_count = len(self.model_groups) - gpu_count

    print(f"  - GPU+CPU variants: {gpu_count}")
    print(f"  - CPU only: {cpu_only_count}")
    print(f"============================\n")


def main():
  parser = argparse.ArgumentParser(description="Generate llama-server config.ini")
  parser.add_argument(
    "--models-dir",
    type=Path,
    default="/data/ai-stack/llm/models",
    help="Directory containing GGUF models",
  )
  parser.add_argument(
    "--output",
    type=Path,
    default="/app/config/config.ini",
    help="Output config.ini path",
  )
  parser.add_argument(
    "--large-model-threshold",
    type=str,
    default="20GB",
    help="Threshold for CPU-only models (e.g., 10GB, 5GB)",
  )
  parser.add_argument(
    "--batch-size",
    type=int,
    default=512,
    help="Default batch size",
  )
  parser.add_argument(
    "--ctx-size",
    type=int,
    default=32768,
    help="Default context length",
  )
  parser.add_argument(
    "--num-threads",
    type=int,
    default=8,
    help="Default number of threads",
  )
  parser.add_argument(
    "--ngl-gpu",
    type=int,
    default=99,
    help="GPU layers for GPU models",
  )
  parser.add_argument(
    "--ngl-cpu",
    type=int,
    default=0,
    help="GPU layers for CPU models (usually 0)",
  )
  parser.add_argument(
    "--routing",
    type=str,
    default="",
    help="Model routing config as JSON: {model_name: 'gpu'|'cpu'|'auto', ...}",
  )

  args = parser.parse_args()

  # Parse large model threshold
  threshold_str = args.large_model_threshold.upper()
  if "GB" in threshold_str:
    large_model_threshold = float(threshold_str.replace("GB", "")) * 1024**3
  elif "MB" in threshold_str:
    large_model_threshold = float(threshold_str.replace("MB", "")) * 1024**2
  else:
    large_model_threshold = float(threshold_str)

  # Parse routing config
  model_routing = {}
  if args.routing:
    import json

    model_routing = json.loads(args.routing)

  # Generate config
  generator = ConfigGenerator(
    models_dir=args.models_dir,
    output_path=args.output,
    large_model_threshold=int(large_model_threshold),
    default_batch_size=args.batch_size,
    default_ctx_size=args.ctx_size,
    default_num_threads=args.num_threads,
    gpu_ngl=args.ngl_gpu,
    cpu_ngl=args.ngl_cpu,
    model_routing=model_routing,
  )

  print("Discovering models...")
  generator.discover_models()
  generator.write_config()
  generator.print_summary()


if __name__ == "__main__":
  main()
